//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoDeliveryServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Id { get; set; }
        public string route_cities { get; set; }
        public long date { get; set; }
        public string vehicle { get; set; }
        public int userid { get; set; }
    
        public virtual User User { get; set; }
    }
}
